# Generated by Django 3.1.7 on 2021-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, to='cores.Character'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeComments',
            field=models.ManyToManyField(blank=True, to='cores.Comment'),
        ),
    ]
