# Generated by Django 3.1.7 on 2021-05-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0003_remove_character_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='characters',
        ),
        migrations.AddField(
            model_name='episode',
            name='characters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='cores.character'),
        ),
    ]
