# Generated by Django 3.1.7 on 2021-06-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0005_auto_20210530_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episodeComments',
        ),
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='episodeComments', to='cores.episode'),
        ),
    ]
