# Generated by Django 3.1.7 on 2021-06-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0007_auto_20210609_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character_id', to='cores.location'),
        ),
    ]
