# Generated by Django 3.1.7 on 2021-06-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0008_auto_20210609_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='location',
        ),
    ]
