# Generated by Django 3.1.7 on 2021-06-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0009_remove_character_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='character_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='cores.character'),
        ),
    ]
